"""
SQL Debugger & Optimizer Environment — FastAPI Server
=====================================================
One-liner wiring: hand the environment factory + typed models
to OpenEnv's create_fastapi_app() and get a production-ready
HTTP + WebSocket server for free.

Endpoints (auto-generated by openenv.core):
  GET  /health       — liveness probe
  GET  /docs         — Swagger UI
  GET  /web          — browser-based interactive playground
  POST /reset        — start new episode
  POST /step         — submit action, receive observation
  GET  /state        — inspect current episode state
  WS   /ws           — persistent WebSocket session (preferred for training)
"""

"""Minimal FastAPI server exposing the environment endpoints required by OpenEnv.

This file provides explicit POST /reset, POST /step, and GET /health routes.
It keeps a small in-memory registry of active environments keyed by episode_id.
"""

import os
from typing import Dict, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Make local package importable
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from env import SQLDebuggerEnv
from models import SQLAction, SQLObservation


app = FastAPI(
  title="OpenEnv Environment HTTP API",
  description="SQL Debugging Environment for OpenEnv Hackathon",
  version="1.0.0",
)

# active environments: episode_id -> environment instance
ENVS: Dict[str, SQLDebuggerEnv] = {}


class ResetRequest(BaseModel):
  task_id: Optional[str] = None
  episode_id: Optional[str] = None


@app.get("/health")
def health() -> dict:
  return {"status": "ok"}


@app.post("/reset", response_model=SQLObservation)
def reset(req: ResetRequest):
  """Start a new episode. Returns the initial observation with episode_id set."""
  env = SQLDebuggerEnv()
  obs = env.reset(episode_id=req.episode_id, task_id=req.task_id)

  # register environment under its episode id
  ep_id = env.state.episode_id
  ENVS[ep_id] = env

  # attach episode_id into the observation model for client convenience
  obs_dict = obs.model_dump()
  obs_dict["episode_id"] = ep_id
  return SQLObservation(**obs_dict)


@app.post("/step", response_model=SQLObservation)
def step(action: SQLAction, episode_id: Optional[str] = None):
  """Execute one step for the specified episode.

  Clients should pass `episode_id` either as a query parameter or use the
  value returned by /reset in the observation's `episode_id` field.
  """
  if not episode_id:
    # if only one env is active, default to it
    if len(ENVS) == 1:
      episode_id = next(iter(ENVS.keys()))
    else:
      raise HTTPException(status_code=400, detail="episode_id required when multiple sessions are active")

  env = ENVS.get(episode_id)
  if env is None:
    raise HTTPException(status_code=404, detail=f"No active episode '{episode_id}'")

  obs = env.step(action)
  obs_dict = obs.model_dump()
  obs_dict["episode_id"] = episode_id
  return SQLObservation(**obs_dict)


@app.get("/_debug/sessions")
def list_sessions():
  """Return a small debug view of active sessions and their DB paths.

  This endpoint is intended for local debugging during development and
  will help validate where per-episode SQLite files are stored.
  """
  return {k: getattr(v, "_db_path", None) for k, v in ENVS.items()}
@app.get("/")
def root():
    return {"message": "SQL Debugger API is running 🚀"}